# -*- coding: utf-8 -*-
"""NLP_mini_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zF1JjE_r0cZlO5PerQ8o7NPdaY3BNARp

# **NLP-Based Toxic Comment Classification with Explainability**

**MINI PROJECT**

**Problem:** Automatically classify online comments as *toxic* or *clean* using NLP-based text classification, and explain individual predictions using LIME (Local Interpretable Model-agnostic Explanations).

**Why this matters:** Online platforms receive far more comments than humans can moderate manually. An automated system can flag toxic content early — but moderators need to *trust* the system's decisions, not just accept a black-box label. That's where explainability comes in.

**Dataset:** Civil Comments (Jigsaw/Google) — hosted on Hugging Face
"""

!pip install lime datasets -q

"""### **Load the Dataset**

We use the **Civil Comments** dataset — built by Jigsaw (same organization behind the original Kaggle Toxic Comment dataset) from real comments on independent news sites. It's hosted on Hugging Face and loads directly with no manual download or Kaggle account needed.

Each comment has a `toxicity` score between 0 and 1 (the fraction of human raters who flagged it as toxic).
"""

from datasets import load_dataset
import pandas as pd

# Loads directly from Hugging Face — no download/upload needed
dataset = load_dataset("google/civil_comments", split="train")

# Convert to pandas and take a manageable sample (full train set is 1.8M rows)
df = dataset.to_pandas().sample(n=30000, random_state=42).reset_index(drop=True)

print("Shape:", df.shape)
df[['text', 'toxicity']].head()

"""### **Create Binary Labels**"""

df['label'] = (df['toxicity'] >= 0.5).astype(int)

print(df['label'].value_counts())
print("\nToxic %:", round(df['label'].mean() * 100, 2), "%")

# Rename for consistency with the rest of the notebook
data = df[['text', 'label']].rename(columns={'text': 'comment_text'}).copy()

"""## **Sample inspection**"""

print("Sample CLEAN comment:\n", data[data['label']==0]['comment_text'].iloc[0], "\n")
print("Sample TOXIC comment:\n", data[data['label']==1]['comment_text'].iloc[0])

print("\nFinal working set shape:", data.shape)
print(data['label'].value_counts())

"""## **Preprocessing**"""

import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords', quiet=True)
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+', '', text)      # remove URLs
    text = re.sub(r'\n', ' ', text)                  # remove newlines
    text = re.sub(r'[^a-z\s]', '', text)              # remove punctuation/numbers
    words = text.split()
    words = [w for w in words if w not in stop_words and len(w) > 1]
    return ' '.join(words)

data['clean_text'] = data['comment_text'].apply(clean_text)
data[['comment_text', 'clean_text']].head()

"""## **Train-Test Split & TF-IDF Vectorization**"""

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X_train, X_test, y_train, y_test = train_test_split(
    data['clean_text'], data['label'], test_size=0.2, random_state=42, stratify=data['label']
)

vectorizer = TfidfVectorizer(max_features=7000, ngram_range=(1, 2))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Train shape:", X_train_tfidf.shape)
print("Test shape:", X_test_tfidf.shape)

"""## **Train the Model**

We use **Logistic Regression** — it's fast, works well with TF-IDF features, and (importantly) is interpretable, which pairs naturally with LIME later. A complex deep learning model might score slightly higher, but we'd lose the ability to explain *why* it made a decision — which is central to this project.
"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_tfidf, y_train)

print("Model trained.")

"""##  **Evaluation**"""

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

y_pred = model.predict(X_test_tfidf)

print(classification_report(y_test, y_pred, target_names=['Clean', 'Toxic']))

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Clean', 'Toxic'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

"""## **Explainability with LIME**

A confusion matrix tells us how often the model is right — but not why it makes a specific prediction. **LIME** answers that: for a single comment, it slightly perturbs the text (removing/changing words) and observes how the prediction changes, then highlights which words pushed the prediction toward "toxic" or "clean."

This is the standout part of the project — it turns a black-box classifier into something you can visually justify.
"""

from lime.lime_text import LimeTextExplainer
from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(vectorizer, model)
explainer = LimeTextExplainer(class_names=['Clean', 'Toxic'])

def explain_comment(text, num_features=8):
    cleaned = clean_text(text)
    exp = explainer.explain_instance(cleaned, pipeline.predict_proba, num_features=num_features)
    print(f"Original comment: {text}")
    print(f"Prediction: {'Toxic' if pipeline.predict([cleaned])[0]==1 else 'Clean'}")
    exp.show_in_notebook(text=True)
    return exp

sample_toxic = data[data['label']==1]['comment_text'].iloc[4]
sample_clean = data[data['label']==0]['comment_text'].iloc[4]

explain_comment(sample_toxic)

explain_comment(sample_clean)

"""Testing it with input comment"""

your_comment = "You are so stupid, nobody wants to hear your opinion"  # change this
explain_comment(your_comment)